export const SCR_A07_LABEL = {
  title: '알림',
  back: '뒤로가기',
  readAll: '모두 읽음',
  refresh: '새로고침',
  loading: '알림을 불러오는 중이에요',
  empty: '알림이 없어요',
  emptyDescription: '새로운 알림이 오면 여기에 보여요',
  loadError: '알림을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
  pageLoadError: '알림을 더 불러오지 못했어요. 다시 시도해 주세요.',
  loadMore: '알림 더 보기',
  loadingMore: '알림을 더 불러오는 중이에요',
  retry: '다시 시도',
  today: '오늘',
  yesterday: '어제',
  unread: '읽지 않음',
  read: '읽음',
  justNow: '방금',
  minutesAgo: (minutes: number) => `${minutes}분 전`,
  hoursAgo: (hours: number) => `${hours}시간 전`,
  yesterdayTime: (time: string) => `어제 ${time}`,
  earlierDate: (month: string, day: string) => `${month}월 ${day}일`,
  earlierTime: (date: string, time: string) => `${date} ${time}`,
  item: (title: string, body: string, time: string, read: boolean) =>
    `${title} ${body} ${time} ${read ? '읽음' : '읽지 않음'}`,
} as const;

export const SCR_A07_NOTIFICATION_SEMANTIC_LABEL = {
  CONFIRMATION: '약속 확정',
  APPROVAL: '승인 응답',
  AMEND: '변경 요청',
  REMINDER: '리마인드',
  FULFILLMENT: '이행 확인',
  RESULT: '이행 결과',
} as const;
