import type { Localized } from '@littlefinger/shared';

const ko = {
  brand: '리틀핑거',
  notifications: '알림',
  advertisement: '광고',
  profile: '마이 프로필',
  back: '뒤로',
  history: '지난 약속 히스토리 보기',
  greeting: '이번 주도 약속을 챙겨볼까요?',
  greetingDescription: '함께 정한 약속을 한눈에 확인해요',
  closestPromise: '가장 가까운 약속',
  activeSection: '진행 중 약속',
  waitingSection: '대기 중 약속',
  noEndDate: '종료일을 정하지 않은 약속',
  activeTab: (count: number) => `진행 중 ${count}`,
  waitingTab: (count: number) => `대기 ${count}`,
  empty: '아직 약속이 없어요. 첫 약속을 만들어보세요',
  emptyDescription: '소중한 사람과 새끼손가락 걸고 지킬 약속을 만들어보세요',
  create: '약속 만들기',
  loading: '약속을 불러오는 중이에요',
  loadError: '약속을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
  retry: '다시 시도',
  retryListAccessibility: '약속 목록 다시 시도',
  retryPageAccessibility: '목록 더 불러오기 다시 시도',
  pageError: '목록을 더 불러오지 못했어요.',
  pinnedTitle: '임박한 약속',
  needsResponse: '이행 확인 필요',
  answerFulfillment: '지켜졌나요? 답하기',
  viewPromise: '약속 보기',
  witness: '증인',
  partnerFallback: '상대방',
  endDate: (value: string) => `종료일 ${value}`,
  parties: (creator: string, partner: string) => `${creator} — ${partner}`,
  profileImage: (nickname: string) => `${nickname} 프로필 사진`,
  delete: '삭제',
  deleteFirstTitle: '초안을 삭제할까요?',
  deleteFirstBody: '삭제한 초안은 되돌릴 수 없어요.',
  deleteContinue: '계속',
  deleteFinalTitle: '정말 삭제할까요?',
  deleteFinalBody: '약속 내용이 기기와 서버에서 모두 사라져요.',
  cancel: '취소',
  open: (title: string) => `${title} 열기`,
  deleteDraft: (title: string) => `${title} 초안 삭제`,
};

// 탭 카운트는 상태 라벨(In progress/Completed) 뒤에 숫자만 붙는 칩 표기라 단복수가 없다.
const en = {
  brand: 'Littlefinger',
  notifications: 'Notifications',
  advertisement: 'Ad',
  profile: 'My profile',
  back: 'Back',
  history: 'View past promise history',
  greeting: 'Shall we check in on your promises?',
  greetingDescription: 'See the promises you made together at a glance',
  closestPromise: 'Closest promise',
  activeSection: 'Promises in progress',
  waitingSection: 'Waiting promises',
  noEndDate: 'No end date set',
  activeTab: (count: number) => `In progress ${count}`,
  waitingTab: (count: number) => `Waiting ${count}`,
  empty: 'No promises yet. Create your first promise',
  emptyDescription: 'Make a pinky promise with someone you care about',
  create: 'Create a promise',
  loading: 'Loading promises',
  loadError: 'Could not load promises. Please try again shortly.',
  retry: 'Try again',
  retryListAccessibility: 'Retry loading promises',
  retryPageAccessibility: 'Retry loading more promises',
  pageError: 'Could not load more promises.',
  pinnedTitle: 'Due soon',
  needsResponse: 'Fulfillment check needed',
  answerFulfillment: 'Was it kept? Respond',
  viewPromise: 'View promise',
  witness: 'Witness',
  partnerFallback: 'Partner',
  endDate: (value: string) => `End date ${value}`,
  parties: (creator: string, partner: string) => `${creator} — ${partner}`,
  profileImage: (nickname: string) => `${nickname}'s profile photo`,
  delete: 'Delete',
  deleteFirstTitle: 'Delete this draft?',
  deleteFirstBody: 'A deleted draft cannot be recovered.',
  deleteContinue: 'Continue',
  deleteFinalTitle: 'Really delete it?',
  deleteFinalBody: 'The promise will be removed from this device and the server.',
  cancel: 'Cancel',
  open: (title: string) => `Open ${title}`,
  deleteDraft: (title: string) => `Delete draft ${title}`,
} satisfies typeof ko;

export const SCR_A02_LABEL: Localized<typeof ko> = { ko, en };
