import { LEGAL_DOCUMENT_LABELS } from '@littlefinger/shared';
import type { ReminderHour } from '@littlefinger/shared';

export const SCR_A08_LABEL = {
  title: '마이',
  back: '뒤로',
  connected: '카카오 계정 연결됨',
  profileImage: (nickname: string) => `${nickname} 프로필 사진`,
  keepRate: '약속 지킴율',
  keepRatePercent: (rate: number) => `${rate}%`,
  keepRateAccessibility: (rate: number) => `약속 지킴율 ${rate}퍼센트`,
  aggregating: '집계 중',
  completed: (count: number) => `완료 ${count}건`,
  broken: (count: number) => `불이행 ${count}건`,
  disputed: (count: number) => `의견 불일치 ${count}건`,
  unresolved: (count: number) => `미확정 종결 ${count}건`,
  active: (count: number) => `진행 중 ${count}건`,
  excluded: '의견 불일치와 미확정 종결은 지킴율 계산에서 제외돼요',
  reminderTitle: '리마인드 설정',
  remindD7: 'D-7 리마인드',
  remindD3: 'D-3 리마인드',
  remindD1: 'D-1 리마인드',
  remindDday: 'D-Day 리마인드',
  reminderHourTitle: '리마인드 발송 시각',
  reminderHour: (hour: ReminderHour) => `리마인드 발송 시각 ${hour}:00`,
  reminderHourValue: (hour: ReminderHour) => `${hour}:00 KST`,
  reminderHourChoice: (hour: ReminderHour) => `${hour}:00`,
  legalTitle: '약관 및 개인정보',
  terms: LEGAL_DOCUMENT_LABELS.TERMS,
  termsAccessibility: `${LEGAL_DOCUMENT_LABELS.TERMS} 열기`,
  privacy: LEGAL_DOCUMENT_LABELS.PRIVACY,
  privacyAccessibility: `${LEGAL_DOCUMENT_LABELS.PRIVACY} 열기`,
  logout: '로그아웃',
  logoutTitle: '로그아웃할까요?',
  logoutBody: '이 기기의 알림 토큰을 해제한 뒤 로그아웃해요.',
  cancel: '취소',
  loading: '프로필을 불러오는 중이에요',
  loadError: '프로필을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
  retry: '다시 시도',
  retryAccessibility: '프로필 다시 시도',
  saveError: '설정을 저장하지 못했어요. 다시 시도해 주세요.',
  logoutError: '로그아웃하지 못했어요. 다시 시도해 주세요.',
} as const;
