export const SCR_A02_LABEL = {
  brand: '리틀핑거',
  notifications: '알림',
  activeTab: (count: number) => `진행 중 ${count}`,
  completedTab: (count: number) => `완료 ${count}`,
  waitingTab: (count: number) => `대기 ${count}`,
  empty: '아직 약속이 없어요. 첫 약속을 만들어보세요',
  emptyDescription: '소중한 사람과 새끼손가락 걸고 지킬 약속을 만들어보세요',
  create: '약속 만들기',
  loading: '약속을 불러오는 중이에요',
  loadError: '약속을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
  participantLoadError: '참여 약속을 불러오지 못했어요.',
  delete: '삭제',
  deleteFirstTitle: '초안을 삭제할까요?',
  deleteFirstBody: '삭제한 초안은 되돌릴 수 없어요.',
  deleteContinue: '계속',
  deleteFinalTitle: '정말 삭제할까요?',
  deleteFinalBody: '약속 내용이 기기와 서버에서 모두 사라져요.',
  cancel: '취소',
  open: (title: string) => `${title} 열기`,
  deleteDraft: (title: string) => `${title} 초안 삭제`,
} as const;
