import { LEGAL_DOCUMENT_LABELS_BY_LOCALE } from '@littlefinger/shared';
import type { Localized, ReminderHour } from '@littlefinger/shared';

const ko = {
  title: '마이',
  back: '뒤로',
  connected: '계정 연결됨',
  nicknameSetup: '닉네임 설정',
  profileImage: (nickname: string) => `${nickname} 프로필 사진`,
  keepRate: '약속 지킴율',
  keepRatePercent: (rate: number) => `${rate}%`,
  keepRateAccessibility: (rate: number) => `약속 지킴율 ${rate}퍼센트`,
  aggregating: '집계 중',
  completed: (count: number) => `완료 ${count}건`,
  broken: (count: number) => `불이행 ${count}건`,
  disputed: (count: number) => `의견 불일치 ${count}건`,
  unresolved: (count: number) => `미확정 종결 ${count}건`,
  active: (count: number) => `진행 중 ${count}건`,
  excluded: '의견 불일치와 미확정 종결은 지킴율 계산에서 제외돼요',
  reminderTitle: '리마인드 설정',
  remindD7: 'D-7 리마인드',
  remindD3: 'D-3 리마인드',
  remindD1: 'D-1 리마인드',
  remindDday: 'D-Day 리마인드',
  reminderHourTitle: '리마인드 발송 시각',
  reminderHour: (hour: ReminderHour) => `리마인드 발송 시각 ${hour}:00`,
  reminderHourValue: (hour: ReminderHour) => `${hour}:00 KST`,
  reminderHourChoice: (hour: ReminderHour) => `${hour}:00`,
  // 언어 행의 제목만 두 언어를 함께 적는다 — 반대 언어 사용자가 이 행을 찾는 단서다.
  languageTitle: '언어 / Language',
  // 선택 상태를 색만으로 말하지 않는다(CLAUDE.md §8-7). 라벨 문구가 상태를 함께 말한다.
  languageSelected: (name: string) => `${name} · 선택됨`,
  languageSelect: (name: string) => `${name}(으)로 보기`,
  legalTitle: '약관 및 개인정보',
  // BY_LOCALE.ko 는 기존 LEGAL_DOCUMENT_LABELS 와 같은 객체다 — as const 리터럴 타입이
  // en 쪽 satisfies 검사를 깨뜨리므로 string 으로 넓혀지는 이 경로를 쓴다.
  terms: LEGAL_DOCUMENT_LABELS_BY_LOCALE.ko.TERMS,
  termsAccessibility: `${LEGAL_DOCUMENT_LABELS_BY_LOCALE.ko.TERMS} 열기`,
  privacy: LEGAL_DOCUMENT_LABELS_BY_LOCALE.ko.PRIVACY,
  privacyAccessibility: `${LEGAL_DOCUMENT_LABELS_BY_LOCALE.ko.PRIVACY} 열기`,
  legalDocumentError: '문서를 열 수 없어요. 잠시 후 다시 시도해 주세요.',
  adsPrivacy: '광고 개인정보 설정',
  adsPrivacyError: '광고 개인정보 설정을 열 수 없어요. 잠시 후 다시 시도해 주세요.',
  logout: '로그아웃',
  logoutTitle: '로그아웃할까요?',
  logoutBody: '이 기기의 알림 토큰을 해제한 뒤 로그아웃해요.',
  cancel: '취소',
  loading: '프로필을 불러오는 중이에요',
  loadError: '프로필을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
  retry: '다시 시도',
  retryAccessibility: '프로필 다시 시도',
  saveError: '설정을 저장하지 못했어요. 다시 시도해 주세요.',
  logoutError: '로그아웃하지 못했어요. 다시 시도해 주세요.',
  blockedUsers: '차단 목록 관리',
  withdraw: '탈퇴',
  withdrawTitle: '탈퇴할까요?',
  withdrawWarning: (count: number) => `진행 중인 약속 ${count}건이 있어요. 탈퇴 후에는 응답할 수 없어요.`,
  withdrawContinue: '계속',
  withdrawFinalTitle: '정말 탈퇴할까요?',
  withdrawFinalBody: '확정된 약속 기록은 상대방의 기록이기도 해서 삭제할 수 없어요. 개인정보는 비식별 처리됩니다.',
  withdrawError: '탈퇴하지 못했어요. 다시 시도해 주세요.',
};

// 통계 문구는 공유 상태 라벨(Completed/Not kept …)을 그대로 앞세운다 — 새 용어 발명 금지.
const en = {
  title: 'Profile',
  back: 'Back',
  connected: 'Account linked',
  nicknameSetup: 'Set nickname',
  profileImage: (nickname: string) => `${nickname}'s profile photo`,
  keepRate: 'Keep rate',
  keepRatePercent: (rate: number) => `${rate}%`,
  keepRateAccessibility: (rate: number) => `Keep rate ${rate} percent`,
  aggregating: 'Calculating',
  completed: (count: number) => `Completed ${count}`,
  broken: (count: number) => `Not kept ${count}`,
  disputed: (count: number) => `Views differ ${count}`,
  unresolved: (count: number) => `Closed unconfirmed ${count}`,
  active: (count: number) => `In progress ${count}`,
  excluded: 'Views differ and closed unconfirmed promises are excluded from the keep rate',
  reminderTitle: 'Reminder settings',
  remindD7: 'D-7 reminder',
  remindD3: 'D-3 reminder',
  remindD1: 'D-1 reminder',
  remindDday: 'D-Day reminder',
  reminderHourTitle: 'Reminder time',
  reminderHour: (hour: ReminderHour) => `Reminder time ${hour}:00`,
  reminderHourValue: (hour: ReminderHour) => `${hour}:00 KST`,
  reminderHourChoice: (hour: ReminderHour) => `${hour}:00`,
  languageTitle: '언어 / Language',
  languageSelected: (name: string) => `${name} · Selected`,
  languageSelect: (name: string) => `View in ${name}`,
  legalTitle: 'Terms and privacy',
  terms: LEGAL_DOCUMENT_LABELS_BY_LOCALE.en.TERMS,
  termsAccessibility: `Open ${LEGAL_DOCUMENT_LABELS_BY_LOCALE.en.TERMS}`,
  privacy: LEGAL_DOCUMENT_LABELS_BY_LOCALE.en.PRIVACY,
  privacyAccessibility: `Open ${LEGAL_DOCUMENT_LABELS_BY_LOCALE.en.PRIVACY}`,
  legalDocumentError: 'Could not open the document. Please try again shortly.',
  adsPrivacy: 'Ad privacy settings',
  adsPrivacyError: 'Could not open ad privacy settings. Please try again shortly.',
  logout: 'Log out',
  logoutTitle: 'Log out?',
  logoutBody: "This unregisters this device's notification token, then logs you out.",
  cancel: 'Cancel',
  loading: 'Loading your profile',
  loadError: 'Could not load your profile. Please try again shortly.',
  retry: 'Try again',
  retryAccessibility: 'Retry loading profile',
  saveError: 'Could not save your settings. Please try again.',
  logoutError: 'Could not log out. Please try again.',
  blockedUsers: 'Manage blocked users',
  withdraw: 'Delete account',
  withdrawTitle: 'Delete your account?',
  withdrawWarning: (count: number) =>
    count === 1
      ? 'You have 1 promise in progress. You cannot respond to it after deleting your account.'
      : `You have ${count} promises in progress. You cannot respond to them after deleting your account.`,
  withdrawContinue: 'Continue',
  withdrawFinalTitle: 'Really delete your account?',
  withdrawFinalBody:
    'Confirmed promise records also belong to your partner, so they cannot be deleted. Your personal data will be de-identified.',
  withdrawError: 'Could not delete your account. Please try again.',
} satisfies typeof ko;

export const SCR_A08_LABEL: Localized<typeof ko> = { ko, en };
