export const SCR_A07_LABEL = {
  title: '알림',
  back: '뒤로가기',
  readAll: '모두 읽음',
  refresh: '새로고침',
  loading: '알림을 불러오는 중이에요',
  empty: '알림이 없어요',
  emptyDescription: '새로운 알림이 오면 여기에 보여요',
  loadError: '알림을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
  retry: '다시 시도',
  today: '오늘',
  yesterday: '어제',
  unread: '읽지 않음',
  read: '읽음',
  justNow: '방금',
  minutesAgo: (minutes: number) => `${minutes}분 전`,
  hoursAgo: (hours: number) => `${hours}시간 전`,
  yesterdayTime: (time: string) => `어제 ${time}`,
  earlierDate: (month: string, day: string) => `${month}월 ${day}일`,
  earlierTime: (date: string, time: string) => `${date} ${time}`,
  item: (title: string, read: boolean) => `${title} ${read ? '읽음' : '읽지 않음'}`,
} as const;
