import {
  KEEPER_LABEL,
  KEEPER_LABEL_BY_LOCALE,
  PARTICIPANT_ROLE_LABEL,
  PARTICIPANT_ROLE_LABEL_BY_LOCALE,
  PROMISE_STATUS_LABEL,
  PROMISE_STATUS_LABEL_BY_LOCALE,
  type Answer,
  type Keeper,
  type Localized,
  type ParticipantRole,
  type PromiseStatus,
} from '@littlefinger/shared';

/**
 * 수치·역할이 끼는 문구는 함수다 — 영어는 단복수와 어순이 갈리므로 문자열 접합으로는
 * 두 문법을 한 형태로 담을 수 없다. 한도 수치는 인자로 받는다(config 상수가 출처).
 */
const ko = {
  title: '이행 확인',
  back: '뒤로가기',
  loading: '이행 확인을 불러오는 중이에요',
  loadError: '이행 확인을 불러오지 못했어요.',
  notFound: '약속을 찾을 수 없어요.',
  retry: '다시 시도',
  question: '약속, 지켜졌나요?',
  sameQuestion: '상대방에게도 같은 질문이 가요',
  answerLegend: '약속을 지켰는지 선택해 주세요',
  answer: {
    KEPT: '지켰어요',
    NOT_KEPT: '안 지켜졌어요',
  } satisfies Record<Answer, string>,
  answerSubtitle: {
    KEPT: '뿌듯한 쪽',
    NOT_KEPT: '솔직한 쪽',
  } satisfies Record<Answer, string>,
  comment: '한 줄 의견',
  optional: '선택',
  commentPlaceholder: '서로에게 남길 말을 적어보세요',
  commentLimit: (max: number) =>
    `한 줄 의견은 ${max}자까지 입력할 수 있어요.`,
  submit: '제출',
  reviseSubmit: '수정 제출',
  evidence: '증빙 사진',
  evidenceAdd: '사진 추가',
  evidenceHint: '상대와 증인에게 공개돼요',
  evidencePermissionDenied: '사진을 선택하려면 사진 접근 권한을 허용해 주세요.',
  evidenceSize: (maxMb: number) =>
    `사진은 장당 ${maxMb}MB까지 올릴 수 있어요.`,
  evidenceType: 'JPEG, PNG, WEBP, HEIC 사진만 올릴 수 있어요.',
  evidenceUploadFailed: (count: number) => `사진 ${count}장을 올리지 못했어요.`,
  evidenceUploading: '업로드 중',
  evidenceReady: '업로드 완료',
  evidenceFailed: '업로드 실패',
  evidenceRetry: '사진 업로드 다시 시도',
  evidenceRemove: (id: string) => `증빙 ${id} 삭제`,
  evidenceOpen: (id: string) => `증빙 ${id} 열기`,
  evidenceBlinded: '신고 접수로 가려진 이미지입니다',
  evidenceExpired: '보관 기간이 만료된 증빙입니다',
  counterpartFirst: '상대방이 먼저 답했어요',
  waiting: '상대의 확인을 기다리고 있습니다.',
  revise: '응답 수정',
  revisionUsed: '응답 수정 기회를 사용했어요.',
  beforeChecking: '종료일 다음 날부터 확인할 수 있습니다.',
  alreadyClosed: '이미 종료된 약속입니다.',
  actionError: '요청을 처리하지 못했어요. 다시 시도해 주세요.',
  disputed: '두 분의 확인이 서로 달라요. 대화로 다시 정해보세요.',
  reopen: '다시 확인 요청하기',
  currentResult: '이번 확인 결과',
  history: '이전 확인 기록',
  roundHistory: (roundNo: number) => `${roundNo}차 확인 기록`,
  submittedAt: '응답 시각',
  noComment: '의견 없음',
  responseDone: (role: Extract<ParticipantRole, 'CREATOR' | 'PARTNER'>) =>
    `${PARTICIPANT_ROLE_LABEL[role]} 응답 완료`,
  responseMissing: (role: Extract<ParticipantRole, 'CREATOR' | 'PARTNER'>) =>
    `${PARTICIPANT_ROLE_LABEL[role]} 미응답`,
  endDate: (date: string) => `종료일 ${date}`,
  keeper: (keeper: Keeper) => `지킬 사람 ${KEEPER_LABEL[keeper]}`,
  status: (status: PromiseStatus) => PROMISE_STATUS_LABEL[status],
  role: (role: Extract<ParticipantRole, 'CREATOR' | 'PARTNER'>) =>
    PARTICIPANT_ROLE_LABEL[role],
};

// DISPUTED 계열 en 문구도 P1(기록자, 판정자 아님)을 지킨다 — 누가 옳은지 암시하지 않는다.
const en = {
  title: 'Fulfillment check',
  back: 'Back',
  loading: 'Loading the fulfillment check',
  loadError: 'Could not load the fulfillment check.',
  notFound: 'Promise not found.',
  retry: 'Try again',
  question: 'Was the promise kept?',
  sameQuestion: 'Your partner gets the same question',
  answerLegend: 'Choose whether the promise was kept',
  answer: {
    KEPT: 'Kept it',
    NOT_KEPT: "Wasn't kept",
  } satisfies Record<Answer, string>,
  answerSubtitle: {
    KEPT: 'The proud one',
    NOT_KEPT: 'The honest one',
  } satisfies Record<Answer, string>,
  comment: 'Comment',
  optional: 'Optional',
  commentPlaceholder: 'Leave a note for each other',
  commentLimit: (max: number) => `Comments can be up to ${max} characters.`,
  submit: 'Submit',
  reviseSubmit: 'Submit revision',
  evidence: 'Evidence photos',
  evidenceAdd: 'Add photo',
  evidenceHint: 'Visible to your partner and witnesses',
  evidencePermissionDenied: 'Allow photo access to choose photos.',
  evidenceSize: (maxMb: number) => `Each photo can be up to ${maxMb}MB.`,
  evidenceType: 'Only JPEG, PNG, WEBP, or HEIC photos can be uploaded.',
  evidenceUploadFailed: (count: number) =>
    count === 1 ? 'Could not upload 1 photo.' : `Could not upload ${count} photos.`,
  evidenceUploading: 'Uploading',
  evidenceReady: 'Uploaded',
  evidenceFailed: 'Upload failed',
  evidenceRetry: 'Retry photo upload',
  evidenceRemove: (id: string) => `Delete evidence ${id}`,
  evidenceOpen: (id: string) => `Open evidence ${id}`,
  evidenceBlinded: 'This image is hidden because of a report',
  evidenceExpired: 'This evidence has passed its retention period',
  counterpartFirst: 'Your partner has already responded',
  waiting: "Waiting for your partner's confirmation.",
  revise: 'Revise response',
  revisionUsed: "You've used your one revision.",
  beforeChecking: 'Checks open the day after the end date.',
  alreadyClosed: 'This promise is already closed.',
  actionError: 'Could not process the request. Please try again.',
  disputed: "Your answers don't match. Talk it over and decide together.",
  reopen: 'Request another check',
  currentResult: 'Result of this check',
  history: 'Past check records',
  roundHistory: (roundNo: number) => `Round ${roundNo} check record`,
  submittedAt: 'Responded at',
  noComment: 'No comment',
  responseDone: (role: Extract<ParticipantRole, 'CREATOR' | 'PARTNER'>) =>
    `${PARTICIPANT_ROLE_LABEL_BY_LOCALE.en[role]} responded`,
  responseMissing: (role: Extract<ParticipantRole, 'CREATOR' | 'PARTNER'>) =>
    `${PARTICIPANT_ROLE_LABEL_BY_LOCALE.en[role]} did not respond`,
  endDate: (date: string) => `End date ${date}`,
  keeper: (keeper: Keeper) => `Kept by ${KEEPER_LABEL_BY_LOCALE.en[keeper]}`,
  status: (status: PromiseStatus) => PROMISE_STATUS_LABEL_BY_LOCALE.en[status],
  role: (role: Extract<ParticipantRole, 'CREATOR' | 'PARTNER'>) =>
    PARTICIPANT_ROLE_LABEL_BY_LOCALE.en[role],
} satisfies typeof ko;

export const SCR_A06_LABEL: Localized<typeof ko> = { ko, en };
