export const SCR_A05_LABEL = {
  title: '약속 상세',
  back: '뒤로',
  loading: '약속 상세를 불러오는 중이에요',
  loadError: '약속 상세를 불러오지 못했어요.',
  notFound: '약속을 찾을 수 없어요.',
  retry: '다시 시도',
  content: '약속 내용',
  category: '카테고리',
  keeper: '지킬 사람',
  endDate: '종료일',
  people: '함께한 사람',
  witnesses: '증인',
  reward: '보상',
  penalty: '벌칙',
  noReward: '기록된 보상이 없어요',
  noPenalty: '기록된 벌칙이 없어요',
  record: '확정 기록',
  approvals: '승인 이력',
  integrityVerified: '기록 일치',
  integrityFailed: '기록 불일치',
  invitation: '초대 상태',
  invitationExpires: '초대 만료',
  amend: '변경 협의',
  before: '현재 내용',
  after: '제안 내용',
  fulfillment: '이행 확인 결과',
  noComment: '남긴 의견이 없어요',
  evidence: '증빙',
  evidenceBlinded: '신고 접수로 가려진 이미지입니다',
  evidenceExpired: '보관 기간이 지난 증빙입니다',
  evidenceOpen: '증빙 사진 열기',
  pendingAction: '초대 관리하기',
  checkingAction: '이행 확인하기',
  disputedAction: '재확인하기',
  shareAction: '공유하기',
  newPromiseAction: '새 약속 만들기',
  actionFailed: '요청을 처리하지 못했어요. 다시 시도해 주세요.',
  amendReadOnly: '변경·파기 응답 기능은 다음 단계에서 제공돼요.',
  statusSubtitle: {
    PENDING: '상대방이 확인하면 약속이 확정돼요',
    ACTIVE: '승인 시각과 기록 지문을 함께 보관하고 있어요',
    AMEND_PENDING: '현재 내용과 제안 내용을 같은 기준으로 보여드려요',
    CHECKING: '두 사람 모두 답하면 결과가 기록돼요',
    COMPLETED: '두 사람 모두 지켜졌다고 확인했어요',
    BROKEN: '두 사람 모두 지켜지지 않았다고 확인했어요',
    DISPUTED: '누가 옳은지 판단하지 않고 두 응답을 그대로 기록해요',
    UNRESOLVED: '응답 기한 안에 두 사람의 확인이 모이지 않았어요',
    DECLINED: '상대방의 거절 기록을 그대로 보관해요',
    CANCELED: '두 사람이 승인한 파기 기록을 보관해요',
  },
} as const;
