import type { Localized } from '@littlefinger/shared';

/**
 * 수치·이름이 끼는 문구는 함수다 — 영어는 단복수와 어순이 갈리므로 문자열 접합으로는
 * 두 문법을 한 형태로 담을 수 없다. 한도 수치는 인자로 받는다(config 상수가 출처).
 */
const scrA05Ko = {
  title: '약속 상세',
  back: '뒤로',
  loading: '약속 상세를 불러오는 중이에요',
  loadError: '약속 상세를 불러오지 못했어요.',
  notFound: '약속을 찾을 수 없어요.',
  retry: '다시 시도',
  content: '약속 내용',
  category: '카테고리',
  keeper: '지킬 사람',
  endDate: '종료일',
  people: '함께한 사람',
  witnesses: '증인',
  reward: '보상',
  penalty: '벌칙',
  noReward: '기록된 보상이 없어요',
  noPenalty: '기록된 벌칙이 없어요',
  dday: '남은 기간',
  record: '확정 기록',
  approvals: '승인 이력',
  invitation: '초대 상태',
  invitationExpires: '초대 만료',
  amend: '변경 협의',
  before: '현재 내용',
  after: '제안 내용',
  fulfillment: '이행 확인 결과',
  noComment: '남긴 의견이 없어요',
  evidence: '증빙',
  evidenceBlinded: '신고 접수로 가려진 이미지입니다',
  evidenceExpired: '보관 기간이 지난 증빙입니다',
  evidenceOpen: '증빙 사진 열기',
  evidenceReport: '증빙 신고',
  evidenceReportTitle: '이 증빙을 신고할까요?',
  evidenceReportBody: '신고하면 이미지가 즉시 가려지고 운영자가 확인해요.',
  reportAction: '신고',
  cancel: '취소',
  userReport: '사용자 신고',
  userReportTitle: '이 사용자를 신고할까요?',
  userReportBody: '기존 약속 기록은 그대로 보존돼요.',
  userBlock: '상대방 차단',
  userBlockTitle: '이 사용자를 차단할까요?',
  userBlockBody: '기존 확정 기록은 바뀌지 않고 새 초대만 제한돼요.',
  blockAction: '차단',
  hideAction: '목록에서 숨기기',
  profileImage: (nickname: string) => `${nickname} 프로필 사진`,
  shareMessage: (title: string, status: string) => `${title} · ${status}`,
  pendingAction: '초대 관리하기',
  checkingAction: '이행 확인하기',
  disputedAction: '재확인하기',
  shareAction: '공유하기',
  newPromiseAction: '새 약속 만들기',
  witnessInviteAction: '증인 초대',
  actionFailed: '요청을 처리하지 못했어요. 다시 시도해 주세요.',
  amendRequestAction: '변경·파기 요청',
  amendWithdrawAction: '요청 철회',
  amendApproveAction: '변경 승인',
  cancelApproveAction: '파기 승인',
  amendDeclineAction: '거절',
  amendReason: '변경·파기 이유',
  amendRequester: '요청자',
  amendRequestedAt: '요청 시각',
  cancelRequested: (nickname: string) => `${nickname}님이 파기를 요청했어요`,
  changedBefore: (label: string) => `변경 전 · ${label}`,
  changedAfter: (label: string) => `변경 후 · ${label}`,
  versionHistoryAction: '버전 이력 보기',
  versionHistoryTitle: '버전 이력',
  versionHistoryLoading: '버전 이력을 불러오는 중이에요',
  versionHistoryEmpty: '저장된 버전이 없어요.',
  versionHistoryClose: '버전 이력 닫기',
  version: (versionNo: number) => `v${versionNo}`,
  versionActivated: '적용 시각',
  versionSuperseded: '종료 시각',
  versionRequester: '요청자',
  versionApprover: '승인자',
  versionApproved: '승인 시각',
  versionReason: '변경 이유',
  contentHash: '내용 지문',
  versionFieldLabel: {
    title: '제목',
    body: '약속 내용',
    category: '카테고리',
    end_date: '종료일',
    keeper: '지킬 사람',
    reward: '보상',
    penalty: '벌칙',
  },
  partnerPending: '상대방 · 초대 대기',
  notifyPartnerHint: '상대는 앱 알림을 받을 수 없어요. 직접 알려주세요.',
  notifyPartnerAction: '상대에게 카톡으로 알리기',
  notifyPartnerMessage: (title: string, url: string | null) =>
    [`${title} 약속을 확인해 주세요.`, url].filter((line) => line !== null).join('\n'),
  checkDeadline: '응답 기한',
  history: '지난 이행 확인',
  round: (roundNo: number) => `${roundNo}차 확인`,
  evidenceCount: (count: number) => (count === 0 ? '증빙 없음' : `증빙 ${count}장`),
  answer: {
    KEPT: '지켰어요',
    NOT_KEPT: '안 지켜졌어요',
  },
  invitationStatus: {
    PENDING: '전달됨',
    USED: '사용됨',
    EXPIRED: '만료됨',
    REVOKED: '무효화됨',
  },
  approvalAction: {
    APPROVE: '승인',
    DECLINE: '거절',
    AMEND_SUGGEST: '수정 제안',
    AMEND_REQUEST: '변경 요청',
    AMEND_APPROVE: '변경 승인',
    AMEND_DECLINE: '변경 거절',
    AMEND_WITHDRAW: '변경 철회',
    CANCEL_REQUEST: '파기 요청',
    CANCEL_APPROVE: '파기 승인',
    CANCEL_DECLINE: '파기 거절',
    WITNESS_SIGN: '증인 확인',
  },
  statusSubtitle: {
    PENDING: '상대방이 확인하면 약속이 확정돼요',
    ACTIVE: '승인 시각과 기록 지문을 함께 보관하고 있어요',
    AMEND_PENDING: '현재 내용과 제안 내용을 같은 기준으로 보여드려요',
    CHECKING: '두 사람 모두 답하면 결과가 기록돼요',
    COMPLETED: '두 사람 모두 지켜졌다고 확인했어요',
    BROKEN: '두 사람 모두 지켜지지 않았다고 확인했어요',
    DISPUTED: '누가 옳은지 판단하지 않고 두 응답을 그대로 기록해요',
    UNRESOLVED: '응답 기한 안에 두 사람의 확인이 모이지 않았어요',
    DECLINED: '상대방의 거절 기록을 그대로 보관해요',
    CANCELED: '두 사람이 승인한 파기 기록을 보관해요',
  },
};

// DISPUTED 계열 en 문구도 P1(기록자, 판정자 아님)을 지킨다 — 누가 옳은지 암시하지 않는다.
const scrA05En = {
  title: 'Promise details',
  back: 'Back',
  loading: 'Loading promise details',
  loadError: 'Could not load the promise details.',
  notFound: 'Promise not found.',
  retry: 'Try again',
  content: 'Promise details',
  category: 'Category',
  keeper: 'Who keeps it',
  endDate: 'End date',
  people: 'People involved',
  witnesses: 'Witnesses',
  reward: 'Reward',
  penalty: 'Penalty',
  noReward: 'No reward recorded',
  noPenalty: 'No penalty recorded',
  dday: 'Time left',
  record: 'Confirmed record',
  approvals: 'Approval history',
  invitation: 'Invite status',
  invitationExpires: 'Invite expires',
  amend: 'Change discussion',
  before: 'Current details',
  after: 'Proposed details',
  fulfillment: 'Fulfillment check results',
  noComment: 'No comment left',
  evidence: 'Evidence',
  evidenceBlinded: 'This image is hidden because of a report',
  evidenceExpired: 'This evidence has passed its retention period',
  evidenceOpen: 'Open evidence photo',
  evidenceReport: 'Report evidence',
  evidenceReportTitle: 'Report this evidence?',
  evidenceReportBody: 'Reporting hides the image immediately and our team reviews it.',
  reportAction: 'Report',
  cancel: 'Cancel',
  userReport: 'Report user',
  userReportTitle: 'Report this user?',
  userReportBody: 'Existing promise records are kept as they are.',
  userBlock: 'Block partner',
  userBlockTitle: 'Block this user?',
  userBlockBody: 'Confirmed records stay unchanged; only new invites are blocked.',
  blockAction: 'Block',
  hideAction: 'Hide from list',
  profileImage: (nickname: string) => `${nickname}'s profile photo`,
  shareMessage: (title: string, status: string) => `${title} · ${status}`,
  pendingAction: 'Manage invite',
  checkingAction: 'Confirm fulfillment',
  disputedAction: 'Check again',
  shareAction: 'Share',
  newPromiseAction: 'Create a new promise',
  witnessInviteAction: 'Invite a witness',
  actionFailed: 'Could not process the request. Please try again.',
  amendRequestAction: 'Request a change or cancellation',
  amendWithdrawAction: 'Withdraw request',
  amendApproveAction: 'Approve change',
  cancelApproveAction: 'Approve cancellation',
  amendDeclineAction: 'Decline',
  amendReason: 'Reason for change or cancellation',
  amendRequester: 'Requested by',
  amendRequestedAt: 'Requested at',
  cancelRequested: (nickname: string) => `${nickname} requested to cancel this promise`,
  changedBefore: (label: string) => `Before · ${label}`,
  changedAfter: (label: string) => `After · ${label}`,
  versionHistoryAction: 'View version history',
  versionHistoryTitle: 'Version history',
  versionHistoryLoading: 'Loading version history',
  versionHistoryEmpty: 'No saved versions.',
  versionHistoryClose: 'Close version history',
  version: (versionNo: number) => `v${versionNo}`,
  versionActivated: 'Applied at',
  versionSuperseded: 'Superseded at',
  versionRequester: 'Requested by',
  versionApprover: 'Approved by',
  versionApproved: 'Approved at',
  versionReason: 'Reason for change',
  contentHash: 'Content fingerprint',
  versionFieldLabel: {
    title: 'Title',
    body: 'Promise details',
    category: 'Category',
    end_date: 'End date',
    keeper: 'Who keeps it',
    reward: 'Reward',
    penalty: 'Penalty',
  },
  partnerPending: 'Partner · invite pending',
  notifyPartnerHint: "Your partner can't receive app notifications. Let them know directly.",
  notifyPartnerAction: 'Tell your partner on KakaoTalk',
  notifyPartnerMessage: (title: string, url: string | null) =>
    [`Please check the promise "${title}".`, url].filter((line) => line !== null).join('\n'),
  checkDeadline: 'Response deadline',
  history: 'Past fulfillment checks',
  round: (roundNo: number) => `Round ${roundNo} check`,
  evidenceCount: (count: number) =>
    count === 0 ? 'No evidence' : count === 1 ? '1 evidence photo' : `${count} evidence photos`,
  answer: {
    KEPT: 'Kept it',
    NOT_KEPT: "Wasn't kept",
  },
  invitationStatus: {
    PENDING: 'Sent',
    USED: 'Used',
    EXPIRED: 'Expired',
    REVOKED: 'Revoked',
  },
  approvalAction: {
    APPROVE: 'Approved',
    DECLINE: 'Declined',
    AMEND_SUGGEST: 'Suggested changes',
    AMEND_REQUEST: 'Requested change',
    AMEND_APPROVE: 'Approved change',
    AMEND_DECLINE: 'Declined change',
    AMEND_WITHDRAW: 'Withdrew change',
    CANCEL_REQUEST: 'Requested cancellation',
    CANCEL_APPROVE: 'Approved cancellation',
    CANCEL_DECLINE: 'Declined cancellation',
    WITNESS_SIGN: 'Witness confirmed',
  },
  statusSubtitle: {
    PENDING: 'The promise is confirmed once your partner reviews it',
    ACTIVE: 'Approval times and the record fingerprint are kept together',
    AMEND_PENDING: 'Current and proposed details are shown on the same terms',
    CHECKING: 'The result is recorded once both of you answer',
    COMPLETED: 'Both of you confirmed the promise was kept',
    BROKEN: "Both of you confirmed the promise wasn't kept",
    DISPUTED: 'Both responses are recorded as they are, without judging who is right',
    UNRESOLVED: "Confirmations from both of you didn't arrive by the response deadline",
    DECLINED: "Your partner's decline is kept on record as it is",
    CANCELED: 'The cancellation both of you approved is kept on record',
  },
} satisfies typeof scrA05Ko;

export const SCR_A05_LABEL: Localized<typeof scrA05Ko> = { ko: scrA05Ko, en: scrA05En };

const mod01Ko = {
  title: '변경·파기 요청',
  close: '변경·파기 요청 닫기',
  amendTab: '내용 변경',
  cancelTab: '파기 요청',
  commonNotice: '상대가 승인하면 적용돼요. 승인 전까지는 지금 약속이 그대로 유지돼요.',
  cancelNotice: '두 사람 모두 동의하면 약속이 파기돼요',
  noChanges: '변경된 내용이 없어요.',
  titleField: '제목',
  bodyField: '약속 내용',
  categoryField: '카테고리',
  endDateField: '종료일',
  endDateSelect: '종료일 선택',
  keeperField: '지킬 사람',
  rewardField: '보상',
  penaltyField: '벌칙',
  reasonField: '변경 이유',
  reasonPlaceholder: '변경이나 파기를 요청하는 이유를 남겨주세요.',
  submit: '요청 보내기',
  submitError: '요청을 보내지 못했어요. 다시 시도해 주세요.',
  cancelConfirmTitle: '약속 파기를 요청할까요?',
  cancelConfirmBody: '상대방이 승인하면 약속이 파기되고 되돌릴 수 없어요.',
  cancelConfirmAction: '파기 요청',
  cancelConfirmDismiss: '돌아가기',
};

const mod01En = {
  title: 'Request a change or cancellation',
  close: 'Close change or cancellation request',
  amendTab: 'Change details',
  cancelTab: 'Request cancellation',
  commonNotice: 'Takes effect once your partner approves. Until then, the promise stays as it is.',
  cancelNotice: 'The promise is canceled once both of you agree',
  noChanges: 'Nothing has been changed.',
  titleField: 'Title',
  bodyField: 'Promise details',
  categoryField: 'Category',
  endDateField: 'End date',
  endDateSelect: 'Choose an end date',
  keeperField: 'Who keeps it',
  rewardField: 'Reward',
  penaltyField: 'Penalty',
  reasonField: 'Reason for change',
  reasonPlaceholder: "Tell your partner why you're requesting this change or cancellation.",
  submit: 'Send request',
  submitError: 'Could not send the request. Please try again.',
  cancelConfirmTitle: 'Request to cancel this promise?',
  cancelConfirmBody: 'Once your partner approves, the promise is canceled and cannot be undone.',
  cancelConfirmAction: 'Request cancellation',
  cancelConfirmDismiss: 'Go back',
} satisfies typeof mod01Ko;

export const MOD_01_LABEL: Localized<typeof mod01Ko> = { ko: mod01Ko, en: mod01En };
