export const SCR_W05_LABEL = {
  title: '증인으로 약속을 확인해 주세요',
  role: '증인은 내용을 확인만 해요 — 누가 옳은지 판정하지 않아요',
  readOnly: '읽기 전용',
  loading: '약속을 불러오는 중이에요',
  loadError: '약속을 불러오지 못했어요. 다시 시도해 주세요.',
  retry: '다시 시도',
  signIn: '카카오 로그인하고 확인하기',
  limitedCreator: (nickname: string) => `${nickname}님의 약속`,
  limitedWait: '약속이 확정되면 전체 내용을 볼 수 있습니다',
  parties: (creator: string, partner: string) => `${creator} · ${partner}의 약속`,
  activatedAt: (value: string) => `${value} 확인`,
  confirmCheckbox: '약속 내용을 확인했습니다',
  sign: '내용을 확인했습니다',
  signHint: '확인하면 확인 시각이 기록돼요',
  signedAt: (value: string) => `${value} 확인 서명`,
  evidencePhoto: '증빙 사진',
  evidenceOpen: '증빙 사진 열기',
  evidenceBlinded: '신고 접수로 가려진 이미지입니다',
  evidenceExpired: '보관 기간이 만료된 증빙입니다',
  noComment: '남긴 의견이 없어요',
  answer: {
    KEPT: '지켰어요',
    NOT_KEPT: '안 지켜졌어요',
  },
  reward: '보상',
  penalty: '벌칙',
  endDate: '종료일',
  keeper: '지킬 사람',
  category: '카테고리',
} as const;
