import type { Localized } from '@littlefinger/shared';

/**
 * SCR-W05 문구. limitedCreator·parties 처럼 조사가 붙는 항목은 함수다 — 영어는 소유격과
 * 어순이 달라 접미 연결로는 두 언어를 다 만족할 수 없다.
 */
const ko = {
  title: '증인으로 약속을 확인해 주세요',
  role: '증인은 내용을 확인만 해요 — 누가 옳은지 판정하지 않아요',
  readOnly: '읽기 전용',
  loading: '약속을 불러오는 중이에요',
  loadError: '약속을 불러오지 못했어요. 다시 시도해 주세요.',
  retry: '다시 시도',
  signIn: '카카오 로그인하고 확인하기',
  signInGoogle: 'Google 로그인하고 확인하기',
  limitedCreator: (nickname: string) => `${nickname}님의 약속`,
  limitedWait: '약속이 확정되면 전체 내용을 볼 수 있습니다',
  parties: (creator: string, partner: string) => `${creator} · ${partner}의 약속`,
  activatedAt: (value: string) => `${value} 확인`,
  confirmCheckbox: '약속 내용을 확인했습니다',
  sign: '내용을 확인했습니다',
  signHint: '확인하면 확인 시각이 기록돼요',
  signedAt: (value: string) => `${value} 확인 서명`,
  leave: '증인 나가기',
  leaveUnsignedWarning: '나가면 이 약속을 더 이상 볼 수 없습니다. 계속하시겠어요?',
  leaveSignedWarning: '서명 기록은 지워지지 않습니다. 계속하시겠어요?',
  leaveStay: '계속 보기',
  leaveConfirm: '나가기',
  leaveComplete: '증인에서 나왔습니다.',
  leaveCompleteAction: '참여 약속으로 이동',
  evidencePhoto: '증빙 사진',
  evidenceOpen: '증빙 사진 열기',
  evidenceBlinded: '신고 접수로 가려진 이미지입니다',
  evidenceExpired: '보관 기간이 만료된 증빙입니다',
  noComment: '남긴 의견이 없어요',
  answer: {
    KEPT: '지켰어요',
    NOT_KEPT: '안 지켜졌어요',
  },
  reward: '보상',
  penalty: '벌칙',
  endDate: '종료일',
  keeper: '지킬 사람',
  category: '카테고리',
};

const en = {
  title: 'Please review this promise as a witness',
  role: 'Witnesses only review the content — they never judge who is right',
  readOnly: 'Read only',
  loading: 'Loading the promise',
  loadError: 'Could not load the promise. Please try again.',
  retry: 'Try again',
  signIn: 'Sign in with Kakao to review',
  signInGoogle: 'Sign in with Google to review',
  limitedCreator: (nickname: string) => `${nickname}'s promise`,
  limitedWait: 'You can see the full details once the promise is confirmed',
  parties: (creator: string, partner: string) => `A promise between ${creator} and ${partner}`,
  activatedAt: (value: string) => `Confirmed ${value}`,
  confirmCheckbox: 'I have reviewed this promise',
  sign: 'I have reviewed the content',
  signHint: 'Your review time will be recorded',
  signedAt: (value: string) => `Confirmation signed ${value}`,
  leave: 'Leave as witness',
  leaveUnsignedWarning: 'If you leave, you can no longer see this promise. Continue?',
  leaveSignedWarning: 'Your signature record will not be deleted. Continue?',
  leaveStay: 'Keep viewing',
  leaveConfirm: 'Leave',
  leaveComplete: 'You have left the witness role.',
  leaveCompleteAction: 'Go to my promises',
  evidencePhoto: 'Evidence photo',
  evidenceOpen: 'Open evidence photo',
  evidenceBlinded: 'This image is hidden due to a report',
  evidenceExpired: 'This evidence has passed its retention period',
  noComment: 'No comment left',
  answer: {
    KEPT: 'Kept',
    NOT_KEPT: 'Not kept',
  },
  reward: 'Reward',
  penalty: 'Penalty',
  endDate: 'End date',
  keeper: 'Who keeps it',
  category: 'Category',
} satisfies typeof ko;

export const SCR_W05_LABEL: Localized<typeof ko> = { ko, en };
