import type { Localized } from '@littlefinger/shared';

/**
 * SCR-W04 문구 카탈로그.
 *
 * 수치가 끼는 문구(N건·N장·N일·N자)는 함수다 — 영어는 단복수와 어순이 갈리므로
 * 문자열 접합으로는 두 문법을 한 형태로 담을 수 없다. 한도 수치도 인자로 받는다:
 * 정책 숫자는 config 상수가 출처이고, 카탈로그에 박으면 그 규칙이 깨진다.
 */
const ko = {
  pageTitle: '참여 중인 약속',
  responseCountBadge: (count: number) => `응답이 필요해요 · ${count}건`,
  kakaoSignInCta: '카카오 로그인',
  googleSignInCta: 'Google 로그인',
  retryCta: '다시 시도',
  emptyCopy: '참여 중인 약속이 아직 없어요',
  myResponsePending: '내 응답 전',
  counterpartResponsePending: '상대방 응답 전',
  counterpartSubmitted: '상대방이 먼저 응답했어요',
  waitingCopy: '상대방의 응답을 기다리고 있어요',
  responseQuestion: '약속이 지켜졌나요?',
  commentLabel: '한 줄 의견',
  submitCta: '응답 제출',
  reviseCta: '응답 수정',
  reviseSubmitCta: '수정 제출',
  reopenCta: '다시 확인 요청하기',
  disputedCopy: '두 분의 확인이 서로 달라요. 대화로 다시 정해보세요.',
  commentLimit: (max: number) => `의견은 ${max}자 이하로 입력해 주세요.`,
  evidenceLabel: '증빙 사진',
  evidenceInputLabel: '증빙 사진 선택',
  evidenceAdd: '사진 추가',
  evidenceHint: '상대와 증인에게 공개돼요',
  evidenceTypeCopy: 'JPEG, PNG, WEBP, HEIC 사진만 올릴 수 있어요.',
  evidenceSizeLimit: (mb: number) => `사진은 장당 ${mb}MB까지 올릴 수 있어요.`,
  evidenceCountLimit: (count: number) => `사진은 최대 ${count}장까지 올릴 수 있어요.`,
  evidenceUploading: '업로드 중',
  evidenceReady: '업로드 완료',
  evidenceFailed: '업로드 실패',
  evidenceRetry: '다시 시도',
  evidenceBlinded: '신고 접수로 가려진 이미지입니다',
  evidenceExpired: '보관 기간이 만료된 증빙입니다',
  evidenceOpenAria: (id: string) => `${id} 증빙 열기`,
  evidenceAlt: (id: string) => `${id} 증빙`,
  removeAria: (name: string) => `${name} 삭제`,
  previewAlt: (name: string) => `${name} 미리보기`,
  amendRequestCta: '변경·파기 요청',
  amendTab: '내용 변경',
  cancelTab: '파기 요청',
  finishTab: '마무리 요청',
  amendSubmitCta: '요청 보내기',
  amendCommonNotice: '상대가 승인하면 적용돼요. 승인 전까지는 지금 약속이 그대로 유지돼요.',
  cancelNotice: '두 사람 모두 동의하면 약속이 파기돼요',
  finishNotice: '상대가 승인한 시각부터 이행 확인과 개인 보관 기간이 시작돼요.',
  noAmendChanges: '변경된 내용이 없어요.',
  amendReasonLabel: '변경 이유',
  amendReasonPlaceholder: '변경이나 파기를 요청하는 이유를 남겨주세요.',
  amendClose: '변경·파기 요청 닫기',
  amendWithdraw: '요청 철회',
  amendApprove: '변경 승인',
  cancelApprove: '파기 승인',
  finishApprove: '마무리 승인',
  amendDecline: '거절',
  versionHistoryCta: '버전 이력 보기',
  versionHistoryTitle: '버전 이력',
  versionHistoryClose: '버전 이력 닫기',
  versionHistoryLoading: '버전 이력을 불러오는 중이에요',
  cancelConfirm: '상대방이 승인하면 약속이 파기되고 되돌릴 수 없어요. 파기를 요청할까요?',
  optionalLabel: '선택',
  requesterLabel: '요청자',
  requestedAtLabel: '요청 시각',
  beforeLabel: '변경 전',
  afterLabel: '변경 후',
  noRewardLabel: '보상 없음',
  noEndDateLabel: '종료일 없음',
  noPenaltyLabel: '벌칙 없음',
  cancelRequested: (nickname: string) => `${nickname}님이 파기를 요청했어요`,
  finishRequested: (nickname: string) => `${nickname}님이 약속 마무리를 요청했어요`,
  amendField: {
    title: '제목',
    body: '약속 내용',
    category: '카테고리',
    end_date: '종료일',
    keeper: '지킬 사람',
    reward: '보상',
    penalty: '벌칙',
  },
  answer: {
    KEPT: '지켰어요',
    NOT_KEPT: '안 지켜졌어요',
  },
  noResponse: '응답 없음',
  responded: '응답 완료',
  notResponded: '미응답',
  deadline: (days: number, at: string) => `응답 기한 ${days}일 · ${at}`,
  endDateMeta: (date: string) => `종료일 ${date}`,
  myAnswer: (answer: string) => `내 응답: ${answer}`,
  roundHistoryTitle: (round: number) => `${round}차 확인 기록`,
};

const en = {
  pageTitle: "Promises you're part of",
  responseCountBadge: (count: number) =>
    count === 1 ? '1 promise needs your response' : `${count} promises need your response`,
  kakaoSignInCta: 'Sign in with Kakao',
  googleSignInCta: 'Sign in with Google',
  retryCta: 'Try again',
  emptyCopy: "You're not part of any promises yet",
  myResponsePending: "You haven't responded yet",
  counterpartResponsePending: "Your partner hasn't responded yet",
  counterpartSubmitted: 'Your partner has already responded',
  waitingCopy: "Waiting for your partner's response",
  responseQuestion: 'Was the promise kept?',
  commentLabel: 'Comment',
  submitCta: 'Submit response',
  reviseCta: 'Revise response',
  reviseSubmitCta: 'Submit revision',
  reopenCta: 'Request another check',
  disputedCopy: "Your answers don't match. Talk it over and decide together.",
  commentLimit: (max: number) => `Keep your comment to ${max} characters or fewer.`,
  evidenceLabel: 'Evidence photos',
  evidenceInputLabel: 'Choose evidence photos',
  evidenceAdd: 'Add photo',
  evidenceHint: 'Visible to your partner and witnesses',
  evidenceTypeCopy: 'Only JPEG, PNG, WEBP, or HEIC photos can be uploaded.',
  evidenceSizeLimit: (mb: number) => `Each photo can be up to ${mb}MB.`,
  evidenceCountLimit: (count: number) =>
    count === 1 ? 'You can upload up to 1 photo.' : `You can upload up to ${count} photos.`,
  evidenceUploading: 'Uploading',
  evidenceReady: 'Uploaded',
  evidenceFailed: 'Upload failed',
  evidenceRetry: 'Try again',
  evidenceBlinded: 'This image is hidden because of a report',
  evidenceExpired: 'This evidence has passed its retention period',
  evidenceOpenAria: (id: string) => `Open evidence ${id}`,
  evidenceAlt: (id: string) => `Evidence ${id}`,
  removeAria: (name: string) => `Delete ${name}`,
  previewAlt: (name: string) => `Preview of ${name}`,
  amendRequestCta: 'Request a change or cancellation',
  amendTab: 'Change details',
  cancelTab: 'Request cancellation',
  finishTab: 'Request finish',
  amendSubmitCta: 'Send request',
  amendCommonNotice:
    'Takes effect once your partner approves. Until then, the promise stays as it is.',
  cancelNotice: 'The promise is canceled once both of you agree',
  finishNotice: 'Once your partner approves, fulfillment checking and personal retention begin.',
  noAmendChanges: 'Nothing has been changed.',
  amendReasonLabel: 'Reason for change',
  amendReasonPlaceholder: "Tell your partner why you're requesting this change or cancellation.",
  amendClose: 'Close change or cancellation request',
  amendWithdraw: 'Withdraw request',
  amendApprove: 'Approve change',
  cancelApprove: 'Approve cancellation',
  finishApprove: 'Approve finish',
  amendDecline: 'Decline',
  versionHistoryCta: 'View version history',
  versionHistoryTitle: 'Version history',
  versionHistoryClose: 'Close version history',
  versionHistoryLoading: 'Loading version history',
  cancelConfirm:
    'Once your partner approves, the promise is canceled and cannot be undone. Request cancellation?',
  optionalLabel: 'Optional',
  requesterLabel: 'Requested by',
  requestedAtLabel: 'Requested at',
  beforeLabel: 'Before',
  afterLabel: 'After',
  noRewardLabel: 'No reward',
  noEndDateLabel: 'No end date',
  noPenaltyLabel: 'No penalty',
  cancelRequested: (nickname: string) => `${nickname} requested to cancel this promise`,
  finishRequested: (nickname: string) => `${nickname} requested to finish this promise`,
  amendField: {
    title: 'Title',
    body: 'Promise details',
    category: 'Category',
    end_date: 'End date',
    keeper: 'Who keeps it',
    reward: 'Reward',
    penalty: 'Penalty',
  },
  answer: {
    KEPT: 'Kept it',
    NOT_KEPT: "Wasn't kept",
  },
  noResponse: 'No response',
  responded: 'Responded',
  notResponded: 'Did not respond',
  deadline: (days: number, at: string) =>
    days === 1 ? `1 day left to respond · ${at}` : `${days} days left to respond · ${at}`,
  endDateMeta: (date: string) => `End date ${date}`,
  myAnswer: (answer: string) => `Your response: ${answer}`,
  roundHistoryTitle: (round: number) => `Round ${round} check record`,
} satisfies typeof ko;

export const SCR_W04_LABEL: Localized<typeof ko> = { ko, en };
